"use client";
import NextTopLoader from "nextjs-toploader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// const metadata: Metadata = {
//   title: "Events Booking App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Event Booking</title>
      <body className={inter.className}>
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
